name: Rust

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Linux Dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    pkg-config \
                    build-essential \
                    libwayland-dev \
                    libxkbcommon-dev \
                    libx11-dev \
                    libxcursor-dev \
                    libxrandr-dev \
                    libxinerama-dev \
                    libxi-dev

            - name: Build
              env:
                  GLFWS_BUILD_FROM_SOURCE: ${{ matrix.os == 'ubuntu-latest' }}
              run: cargo build --release --verbose

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: mineclient-build-${{ matrix.os }}
                  path: |
                      ${{ startsWith(matrix.os, 'ubuntu') && 'target/release/mineclient' || '' }}
                      ${{ startsWith(matrix.os, 'windows') && 'target/release/mineclient.exe' || '' }}
